#!/bin/sh

# [ -t 1 ] || sleep 10

if ! which sysctl &>/dev/null; then
    echo '2500000' > /proc/sys/net/core/rmem_max
fi

/opt/etc/toggle_proxy.sh disable
echo '--------------'
/opt/etc/toggle_proxy.sh enable && date "+%Y%m%d_%H:%M:%S" > /tmp/patch_router_was_run_at
