#!/bin/bash

ssh "$*" '[ -f /opt/etc/toggle_proxy.sh ] && /opt/etc/toggle_proxy.sh disable'

self="$(curl -sS -k https://raw.githubusercontent.com/zw963/deployment_bash/v0.6.0/deploy_start.sh)" && eval "$self"

export target=$1

config=./router/opt/etc/v2ray.json

if [ ! -e "$config" ];then
    echo "Please create ${config} or generate it use deploy_v2ray+ss_to_vps before deploy to router."
    exit
fi

copy "$config" /opt/etc/
copy router/opt/etc/apply_iptables_rule.sh /opt/etc/
copy router/opt/etc/clean_iptables_rule.sh /opt/etc
copy router/opt/etc/toggle_proxy.sh /opt/etc
copy router/opt/etc/enable_swap.sh /opt/etc
copy router/opt/etc/patch_router /opt/etc
copy router/opt/etc/restart_dnsmasq.sh /opt/etc
copy router/opt/etc/update_geosite.sh /opt/etc

if [ -d predownloaded_binary ] && zip_file=$(ls -1 predownloaded_binary/*.zip |head -n1); then
    echo 'Copy predownloaded binary to router ...'
    copy predownloaded_binary/v2ray-linux-arm.zip predownloaded_binary/v2ray-linux-arm.zip
else
    ssh "$*" "rm -rf predownloaded_binary"
fi

deploy_start

set -eu

# --------------------------------------------------------------------------------
#
# Following script will be run on router, please change it to meet your's need.
#
# -------------------------------------------------------------------------------

#
# 如果第一次运行本脚本, 请务必初始化 entware 包管理系统.
# ssh 登陆路由器, 执行 entware-setup.sh, 选择 1'

if ! opkg --version; then
    echo 'Please initialise entware-ng if you run this first time.'
    echo "e.g. plugin your's usb disk, and run \`entware-setup.sh', select 1."
    echo "Run \`opkg --version' failed."
    exit
fi

if [ ! -e /jffs/scripts/services-start ]; then
    cat <<'HEREDOC' > /jffs/scripts/services-start
#!/bin/sh

RC='/opt/etc/init.d/rc.unslung'

i=30
until [ -x "$RC" ] ; do
  i=$(($i-1))
  if [ "$i" -lt 1 ] ; then
    logger "Could not start Entware"
    exit
  fi
  sleep 1
done
$RC start
HEREDOC
fi

v2ray_version=4.26.0
arch=linux-arm

if [ -d predownloaded_binary ]; then
    cd predownloaded_binary && unzip -o *.zip && chmod +x v2ctl* v2ray*
else
    download_and_extract https://github.com/v2ray/v2ray-core/releases/download/v${v2ray_version}/v2ray-${arch}.zip v2ray-v${v2ray_version}
    cd v2ray-v${v2ray_version} && rm -f *.sig && chmod +x v2ctl* v2ray*
fi
v2ray_commands=$(/opt/bin/find -maxdepth 1 -name 'v2ray_*')

for v2ray_command in ./v2ray $v2ray_commands; do
    if $v2ray_command -version &>/dev/null; then
        valid_v2ray_command=$v2ray_command
        valid_v2ctl_command=$(echo $v2ray_command |sed 's#v2ray#v2ctl#')
        break
    else
        valid_v2ray_command=
    fi
done

if [  -z "$valid_v2ray_command" ]; then
    echo 'Not valid v2ray version is supported by current router, please check if download correct version.'
    exit
else
    $valid_v2ray_command -version
fi && cp $valid_v2ray_command $valid_v2ctl_command *.dat /opt/sbin/
echo 'v2ray is installed'

cat <<'HEREDOC' > /opt/etc/init.d/S22v2ray
#!/bin/sh

ENABLED=yes
PROCS=v2ray
ARGS="-config /opt/etc/v2ray.json"
PREARGS=""
DESC=$PROCS
PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[ -z "$(which $PROCS)" ] && exit 0

. /opt/etc/init.d/rc.func
HEREDOC

chmod +x /opt/etc/init.d/S22v2ray

# ----------------------------------------------------
#
# 下面执行一些脚本检查与替换。
#
# ---------------------------------------------------

cd /opt/etc
chmod +x apply_iptables_rule.sh \
      clean_iptables_rule.sh \
      toggle_proxy.sh \
      enable_swap.sh \
      patch_router \
      update_geosite.sh \
      /jffs/scripts/services-start

# ----------------------------------------------------
#
# 启动所需的脚本
#
# ---------------------------------------------------

# 每隔 1 分钟检测下所有的服务是否运行.
add_service wan-start 'cru a run-services "*/1 * * * *" "/jffs/scripts/services-start"'
# 每隔 3 分钟检测下 iptables 是否失效.
add_service wan-start 'cru a run-iptables "*/3 * * * *" "/opt/etc/apply_iptables_rule.sh"'
# 每个 2 天升级一次
# FIXME: newest dlc.dat in domain-list-community not work well with current version V2Ray.
# add_service wan-start 'cru a update_geosites "* * */2 * *" "/opt/etc/update_geosite.sh"'

/jffs/scripts/wan-start

# Because newest asus merlin introduce AMPM, please enable swap file there if need it.
# 打开swap
# echo 'Enabling swap'
# /opt/etc/enable_swap.sh
# add_service post-mount '/opt/etc/enable_swap.sh'

# 如果 DHCP 重新分配 IP 地址时, 会清除 iptables rule, 此时重新应用 iptables
add_service dhcpc-event '/opt/etc/apply_iptables_rule.sh'

set +e
/jffs/scripts/services-stop
set -e
/jffs/scripts/services-start

# 在所有服务启动之后, 运行 /opt/etc/patch_router 为 dnsmasq 追加配置, 并重启 dnsmasq 服务.
add_service services-start '[ -f /tmp/patch_router_was_run_at ] || /opt/etc/patch_router'
/opt/etc/patch_router

echo "Congratulations, [0m[33mDeploy succssful[0m!"
