#!/bin/bash

if [ -z "$*" ]; then
    echo Usage: use_redirect_proxy admin@192.168.50.1
    exit
fi

ssh "$*" 'rm -f /opt/etc/use_fakedns && touch /opt/etc/use_redirect_proxy'
ssh "$*" /opt/etc/patch_router
